set nocount on

--Instance setup
exec sp_configure 'Ad Hoc Distributed Queries',1
exec sp_configure 'xp_cmdshell',1
reconfigure

--default office driver version
EXEC master.dbo.sp_MSset_oledb_prop N'Microsoft.Jet.OLEDB.4.0', N'AllowInProcess', 1 
EXEC master.dbo.sp_MSset_oledb_prop N'Microsoft.Jet.OLEDB.4.0', N'DynamicParameters', 1
GO 

--latest driver version
EXEC sp_MSset_oledb_prop N'Microsoft.ACE.OLEDB.15.0', N'AllowInProcess', 1   
EXEC sp_MSset_oledb_prop N'Microsoft.ACE.OLEDB.15.0', N'DynamicParameters', 1

create table cmd_to_exec(cmd varchar(max) null);

CREATE TABLE [dbo].[AssessmentSummary_stg](
	[Server] [varchar](100) NULL,
	[Instance] [varchar](100) NULL,
	[Schema] [varchar](100) NULL,
	[ObjectType] [nvarchar](255) NULL,
	[NumberofObjects] [varchar](255) NULL,
	[ConversionTimeHrs] [varchar](255) NULL,
	[ConvRate] [varchar](255) NULL
) 

CREATE TABLE [dbo].[AssessmentSummary](
	[Server] [varchar](100) NULL,
	[Instance] [varchar](100) NULL,
	[Schema] [varchar](100) NULL,
	[ObjectType] [nvarchar](255) NULL,
	[NumberofObjects] [float] NULL,
	[ConversionTimeHrs] [float] NULL,
	[ConvRate] [float] NULL
)

USE [SSMAreport]
GO
/****** Object:  StoredProcedure [dbo].[sp_loadAssessmentSummary]    Script Date: 19/05/2017 15:37:56 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
create  procedure [dbo].[sp_loadAssessmentSummary]
@path varchar(500)='C:\cases\COE\SEAL\MSReady\',
@suffix varchar(500)='report.xml_conv.xlsx'
as

set nocount on

--script that load data from excel
truncate table cmd_to_exec
truncate table AssessmentSummary
truncate table AssessmentSummary_stg

declare @cmddos varchar(500)
set @cmddos = 'dir '+@path+' /s /b /a | findstr /R "xml_conv.xlsx"'

insert into cmd_to_exec exec xp_cmdshell @cmddos

delete cmd_to_exec where cmd is null --delete unnecessary emty lines

declare @cmdexec varchar(max)
--set @path = 'C:\cases\COE\SEAL\MSReady\'
--set @suffix ='report.xml_conv.xlsx'

declare c_cmd cursor for 
select cmd 
from cmd_to_exec

declare @cmd varchar(max),
@stmt varchar(max),
@file varchar(max),
@server varchar(max),
@instanceschema varchar(max),
@instance varchar(max),
@schema varchar(max)

open c_cmd
fetch c_cmd into @cmd

while (@@fetch_status=0)
begin

set @file=substring(replace(@cmd,@path,''),1,charindex('\',replace(@cmd,@path,''))-1)
set @server = left(@file,charindex('_',@file)-1)
set @instanceschema=right(@file,len(@file)-len(@server)-1)
set @instance=left(@instanceschema,charindex('_',@instanceschema)-1)
set @schema=right(@instanceschema,len(@instanceschema)-len(@instance)-1)

set @stmt = 'insert [AssessmentSummary_stg] SELECT '''+
@server
+''','''+
@instance
+''','''+
@schema
+''','+
' [Generated by SSMA for Oracle Version 7#0#0],F2,f3,f4'+

+' FROM OPENROWSET(''Microsoft.ACE.OLEDB.15.0'',''Excel 12.0; Database='+@cmd+'; HDR=YES; IMEX=1'',''SELECT * FROM [Assessment Summary$]'')'  

exec (@stmt)

fetch c_cmd into @cmd
end

close c_cmd
deallocate c_cmd

delete from [AssessmentSummary_stg]
where NumberofObjects is null
  or NumberofObjects = 'Number of Objects'

INSERT INTO [dbo].[AssessmentSummary]
           ([Server]
           ,[Instance]
           ,[Schema]
           ,[ObjectType]
           ,[NumberofObjects]
           ,[ConversionTimeHrs]
           ,[ConvRate])
SELECT [Server]
      ,[Instance]
      ,[Schema]
      ,[ObjectType]
      ,convert(float,[NumberofObjects])
      ,convert(float,replace([ConversionTimeHrs],',','.'))
      ,convert(float,replace(replace([ConvRate],'%',''),',','.'))
  FROM [dbo].[AssessmentSummary_stg]

  RETURN



--Exemple d'usage
--USE [MSReady]
--GO

--DECLARE	@return_value int

--EXEC	 [dbo].[sp_loadAssessmentSummary]
--		@path = N'C:\cases\COE\SEAL\MSReady\',
--		@suffix = N'report.xml_conv.xlsx'

--SELECT	'Return Value' = @return_value

--GO
